# Needs porting
# usr/lib/totem/plugins/bbc
usr/lib/totem/plugins/apple-trailers
usr/lib/totem/plugins/autoload-subtitles
usr/lib/totem/plugins/brasero-disc-recorder
usr/lib/totem/plugins/chapters
usr/lib/totem/plugins/dbus
usr/lib/totem/plugins/im-status
usr/lib/totem/plugins/lirc
usr/lib/totem/plugins/media-player-keys
usr/lib/totem/plugins/ontop
usr/lib/totem/plugins/opensubtitles
usr/lib/totem/plugins/properties
usr/lib/totem/plugins/pythonconsole
usr/lib/totem/plugins/recent
usr/lib/totem/plugins/rotation
usr/lib/totem/plugins/save-file
usr/lib/totem/plugins/screensaver
usr/lib/totem/plugins/screenshot
usr/lib/totem/plugins/skipto
usr/lib/totem/plugins/vimeo
usr/lib/totem/plugins/zeitgeist-dp
