# Needs porting
# usr/lib/xplayer/plugins/bbc
usr/lib/xplayer/plugins/apple-trailers
usr/lib/xplayer/plugins/autoload-subtitles
usr/lib/xplayer/plugins/brasero-disc-recorder
usr/lib/xplayer/plugins/chapters
usr/lib/xplayer/plugins/dbus
usr/lib/xplayer/plugins/im-status
usr/lib/xplayer/plugins/lirc
usr/lib/xplayer/plugins/media-player-keys
usr/lib/xplayer/plugins/ontop
usr/lib/xplayer/plugins/opensubtitles
usr/lib/xplayer/plugins/properties
usr/lib/xplayer/plugins/pythonconsole
usr/lib/xplayer/plugins/recent
usr/lib/xplayer/plugins/rotation
usr/lib/xplayer/plugins/screensaver
usr/lib/xplayer/plugins/screenshot
usr/lib/xplayer/plugins/skipto
usr/lib/xplayer/plugins/vimeo
usr/lib/xplayer/plugins/zeitgeist-dp
